# Generated by Django 2.2.5 on 2019-09-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=100)),
                ('locationPhoto', models.ImageField(upload_to='images/location')),
                ('address', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('websiteUrl', models.URLField()),
                ('storeHours', models.CharField(max_length=200)),
                ('uploadSpeed', models.CharField(blank=True, max_length=4, null=True)),
                ('downloadSpeed', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profilePhoto', models.ImageField(upload_to='images/profile')),
                ('homeLocation', models.CharField(max_length=200)),
            ],
        ),
    ]
