# Generated by Django 2.2.5 on 2019-09-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomads_Pal_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='address',
            new_name='locationAddress',
        ),
        migrations.AddField(
            model_name='location',
            name='locationCity',
            field=models.CharField(default='Oregon City', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='locationState',
            field=models.CharField(default='OR', max_length=3),
        ),
        migrations.AddField(
            model_name='location',
            name='locationZipCode',
            field=models.CharField(default='97045', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/location'),
        ),
    ]
