# Generated by Django 2.2.5 on 2019-09-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomads_Pal_app', '0003_auto_20190923_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='downloadSpeed',
            field=models.CharField(default='Not Available', max_length=15),
        ),
        migrations.AlterField(
            model_name='location',
            name='uploadSpeed',
            field=models.CharField(default='Not Available', max_length=15),
        ),
    ]
