# Generated by Django 2.2.5 on 2019-09-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomads_Pal_app', '0005_auto_20190929_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationPhoto',
            field=models.ImageField(default='images/location/default_image.png', upload_to='images/location'),
        ),
    ]
