# Generated by Django 2.2.5 on 2019-10-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomads_Pal_app', '0006_auto_20190929_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationPhoto',
            field=models.ImageField(upload_to='images/location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='storeHours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='websiteUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
